apiVersion: v1
kind: Service
metadata: 
    name: backendservice-service
    labels:
       app: backendservice
spec: 
   selector:
     app: backendservice
   ports:
     - protocol: TCP
       port: 8089
       targetPort: 8089
       #name: http
   #type: ClusterIP