apiVersion: v1
kind: Service
metadata: 
    name: databaseservice-service
    labels:
       app: databaseservice
spec: 
   selector:
     app: databaseservice
   ports:
     - protocol: TCP
       port: 5984
       targetPort: 5984
       #name: http
   #type: ClusterIP