apiVersion: apps/v1
kind: Deployment
metadata: 
   name: frontendservice-deployment
   labels:
     app: frontendservice
spec:
   #minReadySeconds: 3
   #strategy:
     #type: RollingUpdate
     #rollingUpdate: 
        #maxSurge: 1
        #maxUnavailable: 1
   replicas: 1
   selector:
      matchLabels:
         app: frontendservice
   template:
       metadata:
         labels:
           app: frontendservice
       spec:
         containers:
           - name: frontendservice
             image: sereme98/frontend2
             ports:
               - containerPort: 8080
             env:
               - name: BACKEND_HOST
                 value: back-c
               - name: API_URL
                 value: http://"+back-c+":8089/ 