apiVersion: v1
kind: Service
metadata: 
    name: frontendservice-service
    labels:
       app: frontendservice
spec: 
   selector:
     app: frontendservice
   ports:
     - protocol: TCP
       port: 8080
       targetPort: 8080
       name: http
   #type: ClusterIP